# Quick start to Julia

Dan Kersten's notes on getting started with vector and matrix operations, slicing, flattening, reshaping, ranges, and list comprehensions.

This notebook aims to get you started with Julia assuming that you've had some experience with scientific programming, e.g. Matlab, Python/Numpy/, Mathematica or R. 

Here are links to some "cheat-sheets" that might be useful.

https://juliadocs.github.io/Julia-Cheat-Sheet/

https://cheatsheets.quantecon.org/


### Numerical arrays and vector, matrix operations

### Lists
Lists can be used to store
- mixed data (for example, strings, and numbers)
- multiple lists (for example, a list of vectors)
- but our main use will be to store numbers, i.e. vectors

Julia indexing starts at 1 (like Matlab and Mathematica, but not like Python or C!

See:

https://docs.julialang.org/en/v0.6.2/stdlib/arrays/#Base.indices-Tuple{AbstractArray,Any}

https://en.wikibooks.org/wiki/Introducing_Julia/Arrays_and_tuples#Matrix_operations:_using_arrays_as_matrices

and 

https://docs.julialang.org/en/v1.1/stdlib/LinearAlgebra/#Linear-Algebra-1


#### Vectors

In [3]:
cv = [3; 4; 5] # column vector
rv = [2 3. -1] # row vector. 
#Note only the output from last line is printed
#rv is a 1x3 array, while cv is a 3-element array.

1×3 Array{Float64,2}:
 2.0  3.0  -1.0

In [4]:
println(cv,rv)
cv

[3, 4, 5][2.0 3.0 -1.0]


3-element Array{Int64,1}:
 3
 4
 5

#### Matrix construction

In [5]:
A =[1 3 1; 1 1 -1; 3 11 6; 2. -4. 5]

4×3 Array{Float64,2}:
 1.0   3.0   1.0
 1.0   1.0  -1.0
 3.0  11.0   6.0
 2.0  -4.0   5.0

You can also construct a matrix as you would see it math notation

In [6]:
A1 = [1 3  1
     1 1 -1
     3 11 6
    2. -4. 5]; 

# semi-colon prevents output from being printed

#### Matrix vector operations

In [7]:
A*cv # matrix multiplication

4-element Array{Float64,1}:
 20.0
  2.0
 83.0
 15.0

In [8]:
A*rv' # A*rv won't work because rv is a row vector, but will if we transpose rv. 
#rv' is the transpose of rv

4×1 Array{Float64,2}:
  10.0
   6.0
  33.0
 -13.0

In [9]:
A.*A # element by element multiplication
cv'.*rv

1×3 Array{Float64,2}:
 6.0  12.0  -5.0

In [10]:
cv*rv # outer product

3×3 Array{Float64,2}:
  6.0   9.0  -3.0
  8.0  12.0  -4.0
 10.0  15.0  -5.0

In [11]:
B = rand(3,4) # using rand() to make a random 3x3 matrix
B*A # multiple a 3x4 matrix with a 4x3

3×3 Array{Float64,2}:
 2.97275   5.44523   3.90384
 1.43719   0.701643  2.69526
 4.24674  11.0116    5.27502

#### Slicing, accessing elements

In [14]:
rv[1]

2.0

In [15]:
cv[1]

3

In [16]:
A[:,2:3] # second two columns
A[3:4,:] # third and fourth rows
A[[1,4],:]# first and fourth rows

2×3 Array{Float64,2}:
 1.0   3.0  1.0
 2.0  -4.0  5.0

A list can contain elements of any type. The elements can be vectors. Note that list_of_vectors is not a 3x3 Array. It is not a matrix.

Below, after loading LinearAlgebra functions, you can query list_of_vectors for its size, number of dimensions, and length.

In [17]:
list_of_vectors = [[3;4;5], [-1;-2;-3], [0, -10, -20]]

3-element Array{Array{Int64,1},1}:
 [3, 4, 5]    
 [-1, -2, -3] 
 [0, -10, -20]

#### Flattening

In [18]:
temp0=A[:] # or A[1:end] 
# or try: vec(A)
# or collect(Iterators.flatten(A))
# or cat(A...,dims=1)
# test equivalence of type representations, e.g with ==: cat(A...,dims=1)==vec(A)

12-element Array{Float64,1}:
  1.0
  1.0
  3.0
  2.0
  3.0
  1.0
 11.0
 -4.0
  1.0
 -1.0
  6.0
  5.0

In [19]:
reshape(temp0, 4, 3) # use reshape to undo the flattening

4×3 Array{Float64,2}:
 1.0   3.0   1.0
 1.0   1.0  -1.0
 3.0  11.0   6.0
 2.0  -4.0   5.0

#### Ranges

In [20]:
r = 1:5 # defines a compactly stored range
# try 1:.3333:9

1:5

In [21]:
collect(r)# shows what is inside the range

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [22]:
collect(1:.25:4) # Make a list of numbers from 1 to 4 in steps of .25

13-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 
 2.25
 2.5 
 2.75
 3.0 
 3.25
 3.5 
 3.75
 4.0 

Using a range and "list comprehension" to construct a vector

In [23]:
cv2=[i^2 for i in 1:3]
A*cv2

4-element Array{Float64,1}:
  22.0
  -4.0
 101.0
  31.0

In [24]:
A3=[i+j for i in 1:4, j in 1:3] # define a 4x3 matrix using list comprehension

4×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6
 5  6  7

In [26]:
size(A)# returns number of rows and columns as a tuple
ndims(A)# returns the number of dimensions
length(A)# returns the total number of elements

println(size(A)," ",ndims(A)," ",length(A))

(4, 3) 2 12


### Load the *LinearAlgebra* package for more linear algebra operations

In [ ]:
using LinearAlgebra

In [27]:
#Loading the LinearAlgebra package provides the dot product function

dot(rv,rv) # dot product
dot(cv,cv)
println(rv*cv," ",dot(rv,cv)) # compare outputs

UndefVarError: UndefVarError: dot not defined

In [ ]:
S = rand(3,3)
Ss = S + S'; # so that Ss is symmetric. Now try some standard operations. 
#Compare with S instead of Ss

In [ ]:
det(Ss)# inverse should be >0 for inverse to exist
inv(Ss) # inverse
eigvals(Ss) #eigenvalues
eigvecs(Ss) #eigenvectors
rank(Ss) # rank should be 3

In [ ]:
eigvecs(Ss)